name: py3
channels:
  - nvidia
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - anyio=3.7.0
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - blosc=1.21.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.9.2
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - cloudpickle=2.2.1
  - comm=0.1.3
  - cpuonly=2.0
  - cryptography=41.0.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cython=0.29.35
  - cytoolz=0.12.0
  - dask-core=2023.5.1
  - dav1d=1.2.0
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - flit-core=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fsspec=2023.5.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - h5py=3.8.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.28.1
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.1.0
  - ipykernel=6.23.1
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.2.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.6.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.7
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.1.9
  - libcups=2.3.3
  - libcurand=10.3.2.106
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.2
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libglu=9.0.0
  - libgomp=13.1.0
  - libgpg-error=1.46
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpg123=1.31.3
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.4.0
  - nbconvert-core=7.4.0
  - nbconvert-pandoc=7.4.0
  - nbformat=5.9.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - overrides=7.3.1
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.2
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.1
  - plotly=5.14.1
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-image=0.20.0
  - scipy=1.10.1
  - send2trash=1.8.2
  - setuptools=67.8.0
  - sip=6.7.9
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.42.0
  - stack_data=0.6.2
  - svt-av1=1.4.1
  - tbb=2021.9.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.6.2
  - typing_extensions=4.6.2
  - typing_utils=0.1.0
  - tzdata=2023c
  - urllib3=2.0.2
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.2
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - cmake==3.26.3
      - colon3d==1.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - filelock==3.12.0
      - fonttools==4.39.4
      - kiwisolver==1.4.4
      - lit==16.0.5.post0
      - matplotlib==3.8.0.dev1166+gfbf93bd11a
      - mpmath==1.3.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - pyparsing==3.1.0b2
      - pytorch-minimize==0.0.2
      - ruff==0.0.272
      - sympy==1.12
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - triton==2.0.0
