name: py3
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - h5py=3.8.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.7.0
  - pandas=2.0.2
  - pillow=9.4.0
  - plotly=5.14.1
  - py-opencv=4.7.0
  - python=3.11.3
  - pyyaml=6.0
  - scikit-image=0.20.0
  - scipy=1.10.1
  - setuptools=67.8.0
  - toml=0.10.2
  - yaml=0.2.5
  - matplotlib=3.7.1
  - pip:
      - kiwisolver==1.4.4